name: Deploy Dev
on: 
  pull_request:
    branches:
      - 'develop'
    types:
      - 'closed'
jobs:
  call_reusable_workflow:
    uses: gustavolandi/terraform-actions/.github/workflows/deploy-dev.yml@main
    with:
      TF_STATE_BUCKET_NAME: ${{vars.TF_STATE_BUCKET_NAME}}
      TF_STATE_KEY_PATH: ${{vars.TF_STATE_KEY_PATH}}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}